version: '3.8'

services:
    database:
        container_name: db
        restart: always
        image: mysql:latest
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: blog-app
            MYSQL_USER: root
            MYSQL_PASSWORD: pass
        volumes:
            - ./db-data:/var/lib/mysql
